# Generated by Django 3.0.6 on 2020-05-11 04:08

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=200)),
                ('entry_text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('pictures', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos/entry'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Entry')),
            ],
        ),
    ]
