# Generated by Django 3.0.6 on 2020-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200516_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='picture',
            field=models.ImageField(upload_to='photos/entry'),
        ),
    ]
