# Generated by Django 3.0.6 on 2020-05-23 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200516_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 23, 0, 10, 46, 271565, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagem',
            name='picture',
            field=models.ImageField(upload_to='media/photos/entry'),
        ),
    ]
